// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-fiber-demo/controllers"
	"go-fiber-demo/services"
)

// Injectors from wire.go:

func InitializeBaseController() (controllers.BaseController, error) {
	i18n := services.NewI18n()
	baseController := controllers.NewBaseController(i18n)
	return baseController, nil
}
